name: Bug Report
description: Report a bug with Catspeak
labels: ["bug"]
assignees:
  - katsaii
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What is the bug? How did it happen?
      placeholder: A bug happened!! I don't know! Fix it!
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: What was the expected behaviour?
      placeholder: I expected Catspeak to do it for me.
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of Catspeak are you using?
      multiple: false
      options:
        - 0.1.0
        - 0.2.0
        - 0.3.0
        - 1.0.0
        - 1.0.1
        - 1.1.0
        - 1.2.0
        - 1.2.1
        - 1.2.2
        - 1.2.3
        - 2.0.0
        - 2.1.0
        - 2.1.1
        - 2.2.0
        - 2.3.0
        - 2.3.1
        - 2.3.2
        - 2.3.3
        - 3.0.0-beta
        - 3.0.0-beta2
        - 3.0.0-beta3
    validations:
      required: true
